services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P YourStrongPassword123! -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 3

  productmanagement-api:
    image: hamidhaghverdi/productmanagement-api:latest
    build: 
      context: .
      dockerfile: src/ProductManagement.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProductManagementDbtest;User=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  